### ISSUE TITLE
Downloading exploitdb

### ISSUE THREAD

**Issue by mshaneck** [linted/linuxprivchecker#12]
It downloads the exploitdb but then crashes and doesn't realize that it downloaded it. Also, it would be really nice if it just used the exploitdb I already have. I would imagine that most people would use this from Kali, and it should already be there. So maybe prompt the user to enter the location of their exploitdb (or even look in /usr/share/exploitdb) and download only if needed.

**Comment by linted** [comment]
Are you referring to the python3 script's first run when it downloads the submodule? if so that is a limitation of python where it can't import modules that didn't exist before the script began running or something. On the other hand if it is crashing during during actual execution, thats a problem that we can look into.

The reason why I went with the submodule I did was because it is written in python which allows for easy integration with the python scripts. unfortunately that limits us to working with their functionality. I can take a look at their repo again and see if I can finagle it to accept local versions of the database. personally I thought it was kinda convenient that it downloads it for you, however I can definitely see how that is a problem on slower connections.

**Comment by linted** [comment]
@mshaneck, I just looked into it and it seems like the layout of exploitdb's tar file has changed. So in your opinion, and from a usability standpoint, should we just assume who ever is running this will have searchsploit installed on their host machine? if so then we can replace the submodule dependency and associated code with a simple `popen("searchsploit", args)` or something. This will incure the overhead of spawning a bunch of new programs though. 

Thoughts, @5aru ?

**Comment by mshaneck** [comment]
You could check the existence of searchsploit, and if it is there, just use that. Right? If it is not, then you can use your existing method.

**Comment by mshaneck** [comment]
But it is also crashing...

**Comment by mshaneck** [comment]
`Database not found, updating now!

Downloading latest exploits archive...
Traceback (most recent call last):
  File "/home/mshaneck/linuxprivchecker/exploitdb/exploitdb.py", line 82, in download_archive
    file_size = int(resp.info().getheaders("Content-Length")[0])
AttributeError: 'HTTPMessage' object has no attribute 'getheaders'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./privcheckerserver.py", line 58, in <module>
    main()
  File "./privcheckerserver.py", line 48, in main
    exploit = ExploitServer((_IP_, _PORT_), SearchHandler)
  File "./privcheckerserver.py", line 39, in __init__
    exploitdb.ExploitSearch.__init__(self)
  File "/home/mshaneck/linuxprivchecker/exploitdb/exploitdb.py", line 61, in __init__
    self.load_csv()
  File "/home/mshaneck/linuxprivchecker/exploitdb/exploitdb.py", line 129, in load_csv
    self.updatedb(etag)
  File "/home/mshaneck/linuxprivchecker/exploitdb/exploitdb.py", line 259, in updatedb
    self.download_archive()
  File "/home/mshaneck/linuxprivchecker/exploitdb/exploitdb.py", line 85, in download_archive
    file_size = int(resp.info().get("Content-Length"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`

**Comment by linted** [comment]
@5aru and I are unable to replicate the error you are seeing on fresh versions of kali. This might be a problem with your internet connection. Currently I do not recommend spending much time diagnosing this issue as finishing the download will only lead you into another dead end due to the new zip layout. @mshaneck

**Comment by linted** [comment]
Hey, @mshaneck I think the latest pull request should solve your problems. Please take a look and tell me what you think.

**Comment by mshaneck** [comment]
Seems to work. Doesn't download exploit db and starts the server with no errors. I'll let you know more after I try it on a host and connect back to the server.

**Comment by linted** [comment]
@mshaneck the devel branch's server no longer downloads exploit db, ever. It pulls from the default location on kali or you can specify a custom csv file.

**Comment by linted** [comment]
@mshaneck, Had the proposed updates solved your issue?

**Comment by mshaneck** [comment]
I have not thoroughly tested it yet. From what I have done, it works fine.
